# Generated by Django 3.2.3 on 2021-06-01 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('url_slug_pk', models.SlugField(default=models.CharField(max_length=200), max_length=255, primary_key=True, serialize=False)),
                ('url_slug', models.SlugField(default=models.CharField(max_length=200), max_length=255)),
                ('category', models.CharField(default='General', max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('picture_url', models.URLField(max_length=500)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='api.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
