# Generated by Django 3.2.3 on 2021-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchased_amount',
            field=models.IntegerField(default=0),
        ),
    ]
